export const REGISTER='@@register'
export const REGISTER1='@@register1'
export const ALERT_INFO='@@alert_info'
export const ALERT_SUCCESS='@@alert_success'
export const ALERT_ERROR='@@alert_error'
export const ALERT_WARNING='@@alert_warning'
export const LOGIN='@@login'