export const MESSAGE_INFO='@@message_info'
export const MESSAGE_SUCCESS='@@message_success'
export const MESSAGE_ERROR='@@message_error'
export const REGISTER='@@register'
export const ALERT_INFO='@@alert_info'
export const ALERT_SUCCESS='@@alert_success'
export const ALERT_ERROR='@@alert_error'
export const ALERT_WARNING='@@alert_warning'