export const HEAD_MENU='@@head_menu'
export const VERIFACTION='@@verifaction'
export const ALET_MESSAGE='@@alert_message'
export const HEAD_TEST='@@head_test'
export const MOVING_MENU='@@moving_menu'
export const MOVING_INFO='@@moving_info'